### ISSUE TITLE
Add hardware decoding support.

### ISSUE THREAD

**Issue by laichiaheng** [Komorebi-Fork/komorebi#10]
If the hardware decoding is supported, the CPU usage would be much lower.

**Comment by Ev1lbl0w** [comment]
I did some research; the [Clutter backend](https://wiki.gnome.org/Projects/Clutter) *(which komorebi uses)* is already hardware-accelerated, so in theory, this should already be using the GPU to help with video decoding.

These are some tests that I did on my setup *(Intel core i5-8250U, with Intel UHD Graphics 620)*:
- **[Youtube 4K video](https://www.youtube.com/watch?v=LXb3EKWsInQ)**: ~65% CPU usage, Render3D reported ~30% usage
- **Komorebi with 1080p video**: ~10% CPU usage, Render3D reported ~65% usage

Judging by this data, it seems that komorebi is already offloading stuff to the GPU.

But other things should be considered as well for reducing CPU load:

- CPU being used intensely, for example when compiling stuff. (*I already made a dirty hack for komorebi to stop processing video when this happens, but haven't had the time yet to make this a proper feature.)*
- Laptops and battery drain. I will later test how much komorebi drains my laptop battery, and try to think of optimizations *(such as dynamic video playback speed)* if it's really that bad *(which I feel like it is)*.
- Unnecessary rendering when using fullscreen apps, or nearly filling the screen. @Arham4 implemented an auto-pause feature that mitigates this, so this should be enough for many scenarios.
