### ISSUE TITLE
[feature request]Autostart when login the desktop.

### ISSUE THREAD

**Issue by laichiaheng** [Komorebi-Fork/komorebi#11]
Add an option to load it automatically.

**Comment by Ev1lbl0w** [comment]
This should already be handled by whatever distro/desktop environment you're using.

Even if it isn't you can just copy your `/usr/share/applications/komorebi.desktop` file to `~/.config/autostart`.

**Comment by Kangie** [comment]
@laichiaheng is this still an issue?

**Comment by laichiaheng** [comment]
> @laichiaheng is this still an issue?

Not an issue, just a request.

**Comment by Ev1lbl0w** [comment]
After second thought, I feel this should be implemented, even with a very trivial solution/steps. A lot of other apps implement this anyways, and it's much simpler for the end user.

**Comment by Kangie** [comment]
So a checkbox option that adds / removes an entry from
 `$XDG_CONFIG_HOME/autostart`? 

I don't see it hurting anything, or being too complex.

**Comment by Ev1lbl0w** [comment]
> So a checkbox option that adds / removes an entry from
$XDG_CONFIG_HOME/autostart?

Yeah, I think it's *that* simple :stuck_out_tongue:

**Comment by laichiaheng** [comment]
> So a checkbox option that adds / removes an entry from
> `$XDG_CONFIG_HOME/autostart`?
> 
> I don't see it hurting anything, or being too complex.

It just doesn't make sense to do it manually for normal users.
