### ISSUE TITLE
[ENHANCEMENT]: Improve user documentation.

### ISSUE THREAD

**Issue by caelwithcats** [Komorebi-Fork/komorebi#37]
It makes a folder in ~/.config/komorebi/wallpapers. Now what?

**Comment by Ev1lbl0w** [comment]
You should use `komorebi-wallpaper-creator` *(or search for **Wallpaper Creator**)* to make new wallpapers.

**Comment by Kangie** [comment]
In short, you should run 'komorebi' (it should be available from your launcher), if not you can run it from the terminal.

Komorebi will replace your desktop wallpaper with a fullscreen application, providing access to its wallpapers (etc.)

Currently, You can right-click on the desktop (once Komorebi is running) to change the wallpaper. 

A separate application komorebi-wallpaper-creator can be launched to create new wallpapers from videos, images, or web pages.

**Comment by caelwithcats** [comment]
@Kangie why does it stop playing when I switch windows

**Comment by Kangie** [comment]
That's an option that you can change. Right-click on the desktop, select 'Desktop Preferences' and uncheck 'Pause video playback on un-focus'.

This is desired behaviour; On systems with thermal constraints (laptops, etc.) or those can't handle video playback all of the time. 

Are you running on a multi-screen setup, try `komorebi --single-screen`.

**Comment by Kangie** [comment]
Haven't heard back in a couple of days, can't diagnose just from a segfault, and don't have any information about the environment.

User documentation updated so that the 'no indication that it's doing anything if you can't see the desktop' behaviour is explicitly called out.
