### ISSUE TITLE
Does not scale / stretch on Elementary OS

### ISSUE THREAD

**Issue by grand-lotus-iroh** [Komorebi-Fork/komorebi#40]
Hi. Might you have any idear why wallpaper does not scale or fit 1920 x 1080 screen?

Is it just something that I see because I'm using Elementary OS or perhaps you too have this?

![image](https://user-images.githubusercontent.com/1291364/92712839-3912db80-f328-11ea-8276-fabded453670.png)

**Comment by Ev1lbl0w** [comment]
#36 should fix this, but you'll have to compile it yourself for now until it's included in an upcoming release.

@Kangie maybe we should prepare a 2.2.1 version soon?

**Comment by Kangie** [comment]
Agree. I haven't had time to sort out the OFL stuff that would hopefully let us get the package into the debian repos (and that I wanted to get done before the nextt release) but I have all of the info that I need. I should have time to work on it this weekend. Do you have anything else that you want to merge before 2.2.1? If not I'll submit my PR when it's ready (we need to include a copy of the OFL and attribute the sources). 

After that it should be a matter of updating the packaging (which I'll do as I generate the deb for the release). Aim for a release this weekend - I want to get this

**Comment by Ev1lbl0w** [comment]
Well for now I'm not working on any major bugfixing or feature *(since I'm porting the code to the new structure)*, so go ahead!

@grand-lotus-iroh if you have the time, could you try compiling the latest version to ensure your issue is fixed? I've tested on a VM, but it would be more reassuring on a "real environment" :stuck_out_tongue:

**Comment by Ev1lbl0w** [comment]
Closing this issue as v2.2.1 was released. If this bug is still present, please open up another issue.
