### ISSUE TITLE
Komorebi crashes a few seconds after first start, then instantly after any other booting

### ISSUE THREAD

**Issue by Susorodni** [Komorebi-Fork/komorebi#47]
I want to point out that I have dual monitors.
Has this been a problem? When will it be fixed?
The only error message I receive is "Komorebi crashed with signal 5"

**Comment by Ev1lbl0w** [comment]
Yes, take a look at #18. For now there's not a "quick" solution, as it's a problem with the backend *(Clutter)*, and since it's basically deprecated, we will have to move to something else *(probably GTK4 when it releases later this year)*
