### ISSUE TITLE
Use local web page as wallpaper

### ISSUE THREAD

**Issue by Z-Y00** [Komorebi-Fork/komorebi#53]
Hi, I want to use a local web page as wallpaper.
I tried " file:///home/..../fooo.html "
But failed, is there any way to do this?
Thanks

**Comment by Ev1lbl0w** [comment]
This has been implemented already with #7; there is no file dialog to choose a local file, but you can just input your `file:///home/..../fooo.html` string in the wallpaper creation dialog, and it should work.

**Comment by Z-Y00** [comment]
thanks a lot!
