### ISSUE TITLE
cant remove komorebi

### ISSUE THREAD

**Issue by zhoudong777** [Komorebi-Fork/komorebi#54]
I installed komorebi on ubuntu16.04 and installed it by compiling it. After installation, I found that it was not available at all.Then I want to uninstall, but I can't uninstall anyway, that is, I used all the methods you mentioned.So I would like to ask how to uninstall it? Now komorebi has affected my normal use of the computer

**Comment by Ev1lbl0w** [comment]
What is your version of Komorebi? (run `komorebi --version`)

What was the output of the uninstall command? (`sudo ninja uninstall`)

**Comment by zhoudong777** [comment]
It should be the previous version, because running komorebi --version does not display the version.Because I deleted all the source packages, I cannot run sudo ninja uninstall now.When it was not deleted before, it showed that there was no ninja command

**Comment by Ev1lbl0w** [comment]
See if you have the paths `/System/Applications` and `/System/Resources` on your root system. If yes, it means it's and old version of Komorebi *(before this fork)*, that doesn't have proper uninstall instructions. If that's the case, follow [this](https://github.com/cheesecakeufo/komorebi/issues/232) workaround to manually remove it.

**Comment by zhoudong777** [comment]
The problem is solved. Thanks!
