### ISSUE TITLE
[BUG] Video wallpapers crash it in Ubuntu 20.10

### ISSUE THREAD

**Issue by gekonto** [Komorebi-Fork/komorebi#56]
hello, I wrote it originally on the 2.1 version but I thought that since the problem continued through the fork version I should write it here, just in case this helps someone else, original issue here: [https://github.com/cheesecakeufo/komorebi/issues/246](url)

**Comment by Ev1lbl0w** [comment]
Something just ocurred to me; try installing `gstreamer1.0-libav`, maybe that's what's missing:

`sudo apt install gstreamer1.0-libav`

**Comment by gekonto** [comment]
no, it is installed, I tried removing it just in case that's the problem but it wasn't so I reinstalled it. So no, that's not it, something else messes it up

**Comment by Ev1lbl0w** [comment]
Hi, so today I finally got some time to look this up. I created a fresh 20.10 VM, and was able to install komorebi without any issue; so the problem must be something in the upgrade that messed it up, somehow.

If it seems related to video wallpapers, then are you able to watch videos without any issue? Try using `mpv` like this to check for hardware acceleration:

```
mpv -hwdec myVideo.mp4
```

**Comment by gekonto** [comment]
yeah, I watch videos with no trouble, maybe if I completely remove komorebi from my computer fixes it just in case upgrade messed it up, I will try this and let you know

**Comment by gekonto** [comment]
nope, didn't work

**Comment by gekonto** [comment]
d

**Comment by Ev1lbl0w** [comment]
Yes, but did you try the command I pasted above?

**Comment by gekonto** [comment]
yes, it worked fine
