### ISSUE TITLE
[BUG] Komorebi video playback colors turn pink and yellow

### ISSUE THREAD

**Issue by Smeltie** [Komorebi-Fork/komorebi#58]
The video playback works but all the colors are messed up.
No matter what i do it won't just display with the right colors.
The videos themselves work just not when played through Komorebi.
I am using Garuda Linux which makes use of KDE Plasma.

see included image as an example:
https://imgur.com/a/LxTq7o5
No matter which video is displayed they all become weirdly colored.

**Comment by Ev1lbl0w** [comment]
Take a look at https://github.com/cheesecakeufo/komorebi/issues/149 and https://github.com/Komorebi-Fork/komorebi/issues/50.

It's basically an issue with the VAAPI driver and Gstreamer, not Komorebi.

Try using this workaround: https://github.com/cheesecakeufo/komorebi/issues/149#issuecomment-550097277; if it doesn't fix, well, you can temporarily uninstall the driver to make it work again.

**Comment by Ev1lbl0w** [comment]
Closing this as lack of response whether it worked or not; feel free to reopen this if it didn't work

**Comment by ToxicDragon** [comment]
@Ev1lbl0w Tested the workaround on Ubuntu 20.10 with an AMD graphics card (RX 580) which worked flawlessly.

**Comment by Smeltie** [comment]
> Closing this as lack of response whether it worked or not; feel free to reopen this if it didn't work

Yeah, my bad.
The laptop i experienced this on had to go into warranty due to a broken touchscreen.
I’ve only gotten it back a few hours ago.
Thanks for the answer it’s much appreciated.
