### ISSUE TITLE
Feature request : Local web page?

### ISSUE THREAD

**Issue by minhducsun2002** [Komorebi-Fork/komorebi#6]
It would be nice if local web pages are supported, since Internet isn't always available.

**Comment by Ev1lbl0w** [comment]
Thanks for the suggestion. I don't have the time to flesh this out more right now, but for now, you should be able to specify all types of URI's and not just HTTP links; so, to add, for example, `~/myFolder/myWebsite.html`, type this in the URL text field:

`file:///home/yourname/myFolder/myWebsite.html`

**Comment by redbrain** [comment]
i tried setting up apache and using localhost but that was very much of a workaround and i got an error anyways. consider pr #7 .

**Comment by minhducsun2002** [comment]
I am aware of the `file:///` protocol. Actually, I even found the check for `http` in the source code. Thank you anyway for your PR.
