### ISSUE TITLE
An option to mute sound of video as wallpaper

### ISSUE THREAD

**Issue by oyinbo-pikin** [Komorebi-Fork/komorebi#61]
It would be nice to have an option to mute the sound of a video used as a wallpaper whenever. Maybe a button where you can toggle sound on a video.

**Comment by Arham4** [comment]
That is already a feature I made.

**Comment by Arham4** [comment]
That is already a feature I made.

![image_646602ed-4814-4353-915a-bbeee4a628ab20210114_235022](https://user-images.githubusercontent.com/2886217/104686830-a615f380-56c3-11eb-930a-0f1641fecd12.jpg)
