### ISSUE TITLE
How to uninstall kamorebi? I am using ubuntu 18.04.

### ISSUE THREAD

**Issue by aniketbalkhande** [Komorebi-Fork/komorebi#62]
Hello, 

I have downloaded kamorebi  using terminal commands .
                     First downloaded the komorebi-2.1-64-bit.deb package.
Then in terminal have run the commad: 
                     sudo apt install gstreamer1.0-libav

Now  to Uninstall Kamorebi and wallpaper creater I have tried These commands :
                     sudo rm -rf /System/Resources/Komorebi 
                     sudo rm -rf /System/Applications/komorebi

Also tried this command:
                    curl -s https://raw.githubusercontent.com/Komorebi-Fork/komorebi/master/data/Other/postrm | bash -s

The result of these :
              ->  The live video wallpaper is stopped playing and just snoozed.
              ->  But I can't change my desktop wallpaper and also the same desktop behaviour is there just like when the Komerebi was up and running although I have removed both  kamorebi and wallpaper creater desktop applications from ubuntu store.  

Is there any other way to uninstall.
Please Help! In these case. Thank you.

**Comment by Ev1lbl0w** [comment]
Take a look at the workaround at https://github.com/cheesecakeufo/komorebi/issues/249; Komorebi is likely uninstalled *(easiest way to check is just try running `komorebi` on the terminal)*, but it has modified some settings for the GNOME shell, and doesn't undo them on uninstall.

**Comment by aniketbalkhande** [comment]
Yes, you are right. After I did a restart to my system, it's gets back to normal. So it was already uninstalled and the only thing was needed is just a restart. Thank you.
