### ISSUE TITLE
No video wallpapers showing

### ISSUE THREAD

**Issue by JOSEG-1557** [Komorebi-Fork/komorebi#64]
Hi i installed komorebi on opensuse leap 15.2 but video wallpapers show blackscreen. i dont see any error or missing dependencies

**Comment by Ev1lbl0w** [comment]
When you choose a wallpaper, does it show any warning of *"gstreamer-libav missing, you won't be able to set video wallpapers..."*?

How did you install? Did you use the RPM package, or did you compile it by yourself?

Can you try [this](https://github.com/Komorebi-Fork/komorebi/wiki/Improve-video-wallpapers-performance#ensure-hardware-decoding-is-working) from the guide to ensure hardware decoding is working?

**Comment by JOSEG-1557** [comment]
> When you choose a wallpaper, does it show any warning of _"gstreamer-libav missing, you won't be able to set video wallpapers..."_?
> 
> How did you install? Did you use the RPM package, or did you compile it by yourself?
> 
> Can you try [this](https://github.com/Komorebi-Fork/komorebi/wiki/Improve-video-wallpapers-performance#ensure-hardware-decoding-is-working) from the guide to ensure hardware decoding is working?

Will see that info... i used komorebi rpm package and opensuse software gstreamer package. But in my case i detected that video is not showing but the sound of it is on. i dont know why that can happen

**Comment by Ev1lbl0w** [comment]
> But in my case i detected that video is not showing but the sound of it is on.

Huum, it might be a problem of the hardware driver itself in that case. There is a proposed [workaround](https://github.com/cheesecakeufo/komorebi/issues/149#issuecomment-550097277) for issues with the driver, but if that doesn't work, you'll have to uninstall the driver temporarily while there's no solution.

I don't know the exact package name on Fedora/OpenSUSE, but it should be `gstreamer1-libav`. If the above workaround doesn't work, try uninstalling this.
