### ISSUE TITLE
Doesn't work on wayland

### ISSUE THREAD

**Issue by GitGangGuy** [Komorebi-Fork/komorebi#67]
This Komorebi Fork apparently still doesn't work on Wayland (which has been the default display server mode in GNOME for quite a while now). Would it be possible to add support?

**Comment by Ev1lbl0w** [comment]
Yes, this is definitely something that needs to be supported sooner than later.

I did some preliminary testing a few months ago, and I believe there is nothing specifically preventing it from working on Wayland. If you wish to test on your system, comment/remove these lines:

https://github.com/Komorebi-Fork/komorebi/blob/886ee35c9afb0d9e146e9ca4882efcb412a3ebdc/src/Main.vala#L28-L33

It would be nice to get a confirmation that there are no issues in Wayland indeed :slightly_smiling_face:

**Comment by GitGangGuy** [comment]
Thanks for responding so quickly and forward coming, but I currently can't find the time to try your fix out and I've moved to a solution which works even better for me. Thank you for keeping this great project alive! 😄

**Comment by 7RST1** [comment]
This should be reopened, no? Although you've found a workaround, this still is a totally valid feature request.

I tried running it with Wayland, and it seems to work fine, except I am not able to right click on the desktop. I get the normal right-click menu without komorebi menu.
