### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by Exspiravit** [Komorebi-Fork/komorebi#8]
Hi people i see your conversation in original repo and come here, maybe your are the most  reliable team to continue with komorebi app :fox_face: 
I would like to ask you if you already have a date in mind for the new release.

**Comment by SSpecken** [comment]
Dear Komorebi-Fork team,

thanks a lot for keeping this really great project alive!

**Comment by Kangie** [comment]
Look forward to seeing something around the start of next month.

**Comment by Kangie** [comment]
Sorry, linked this to a PR that closed it too early. 

2.2.0 is out, grab a copy from the releases page!
