### ISSUE TITLE
Suggestion/Request: Flathub Software Host/Fork Alternative

### ISSUE THREAD

**Issue by ribbybbir** [Komorebi-Fork/komorebi#84]
Hello Komorebi-Fork,

Komorebi is quite the popular program for GNU/Linux. I must say that it shouldn't be forgotten. I suggest to put a fork of Komorebi-Fork's work to Flathub, flathub.org. Flathub is technically a easy go to popular non system software server/repository site. It usually hosts most up-to-date of popular applications for a variety of operating system softwares. It also have sandbox protocols of its hosted applications. I think Komorebi should be in there too! Operating system servers/repositories don't usually do experimental software hosting. Their job is to ensure the stability of operating systems than test non system software. Still, I wouldn't want this project to just pass and be forgotten. Would like to see the desktop screen to host videos and sites for a more lively experience for quite some time. I'm glad that Komorebi still exists under active/current development!

You guys should probably open an announce in the original developer's page of the recent move. I'm also glad that there is no more personal package archive (PPA), since there is no active developer/author update. Misconfigured PPAs interfere with normal system updates and upgrades.

Sincerely,
ribbybbir

**Comment by heidiwenger** [comment]
Yes! Very much this! A flatpak (or a snap package) would makes things much more straightforward and simple.
